### ISSUE TITLE
Deploy via Vercel

### ISSUE THREAD

**Issue by kphan32** [GTBitsOfGood/boggers#12]
### Description
BoG has historically used Vercel, but recent changes have disabled automatic deployments. Luckily in the past a very cool BoG member wrote [this](https://github.com/GTBitsOfGood/bgc-safety-f2021/blob/main/.github/workflows/main.yml) GitHub action to get around the restrictions.

### Acceptance Criteria
[ ] On PR, deploy to Vercel and link to PR
[ ] On merge to main, deploy to prod
[ ] The `README` is updated with instructions on how to setup the GitHub action

**Comment by samarth52** [comment]
Closed with PR https://github.com/GTBitsOfGood/boggers/pull/15
